### ISSUE TITLE
Soon™ 5 months ago...

### ISSUE THREAD

**Issue by zvodd** [Radeon-ProRender/Blender#1] opened 2017-04-13 10:36 UTC
Was it just hype, to sell GPUs, then not deliver?

**Comment by jadelion** [comment] 2017-04-13 19:19
Well it is beta testing now

**Comment by zvodd** [comment] 2017-04-15 08:48
Is there somewhere the public can get access to the beta releases?

**Comment by dreamswan** [comment] 2017-04-15 17:34
It's in closed beta but here is where you can apply. I signed up but don't have a AMD GPU currently so never heard back. http://www.amdsurveys.com/se/5A1E27D248DC77A1

**Comment by marchante0** [comment] 2018-03-24 19:00
So... I've seen download links, those annoying .run, but where's the source?

**Comment by bsavery** [comment] 2018-03-24 19:04
The plugin is all in python when you install it there's the source.

**Comment by ivalylo** [comment] 2018-03-24 19:26
There is no source, it's a proprietary renderer... What you have is just the exporter.

**Comment by bsavery** [comment] 2018-03-24 21:28
Hi ivalylo.  If you're interested in source for renderer, we'd love to talk to you (and is available).  What is it you're hoping to do with it?  Feel free to contact me at brian.savery (at) amd .  However if you're looking to just get access to easy source we have an open source version which is similar in many ways to the one in the distributed plugin.  https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRender-Baikal

**Comment by ivalylo** [comment] 2018-04-08 17:29
Just to say, I didn't get any answer to my email. I would prefer to get at least the "we don't care" in written form. Shows some respect. Also, I have big quality concerns with ProRender. Just add standard monkey with subdivision. It doesn't look right at all... If you add PBR material, the metalness is reversed - 0 makes it metal, 1 makes it dielectric. Where is the IOR? No, it doesn't make sense (especially in PBR) to control the specularity only from the metalness. Microfacet reflections/refractions have ... "diffuse color"!?! They are also missing anisotropy, for which you must use... separate anisotropy Ward. Why? Both GGX and Beckmann which are the de facto standard microfacet models today support anisotopy. What are you using - Phong? There is absolutely no reason for this Ward node. There is also no reason for separate specular reflection and refraction nodes. The subsurface node looks like slight modification of the generic volumetric, it's not actual fast subsurface approximation. If you increase the destiny, you will start to see faceting caused by not taking into account the smooth normals. Add subdivision to fix the faceting, and some parts of the geometry are now missing.

http://www.image-share.com/ijpg-3719-117.html

This is just in 10 min test. In my email I said that I'm bigger fan of Cycles, it's open, it's high quality, it deserves more publicity. It's difficult for me to figure out what exactly AMD is trying to achieve with ProRender. I know I'm highly critical, but this is only because as software developer and consumer, I would prefer not to have single player on the market, namely NVIDIA. I would prefer AMD to succeed. But AMD slept for so many years... Oh boy... AMD lost so many companies which were practically forced to use CUDA. I know since I worked in such company... I'm trying to see how ProRender can fix all that... I'm really trying... For the sake of all the users out there who don't want a monopoly market. But ProRender looks to me "too little, too late"... I hope I'm wrong...

**Comment by bsavery** [comment] 2018-04-09 04:09
That is an odd problem with subsurface for which I will investigate.  With regards to your email my apologies as I have many things going on, and you'll understand have to focus on commercial customers first.  

WRT your various node questions.  We specifically created the Uber shader and PBR to cover the 99% of material issues.  The PBR shader should behave similarly to Cycles' Principled shader (which also does not have an ior value for specular response).  Uber is a more advanced version with anisotropy, (and uses beckmann fyi).  Metalness being inverted has been fixed in the past, not sure if you have an older version.  Either way there will be an update release on monday which might address a few of your concerns.  Please take another look and keep it respectful.  I will respond to your email.  However if you're looking to just test the render engine, you can participate in the discord discussion here:  https://discord.gg/3HDcP8

**Closed** 2018-05-11 15:14 UTC
